# Generated by Django 4.2.7 on 2023-11-30 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commentlike_unique_comment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'heic'])]),
        ),
    ]
